tick_rate = 24

[ui]
use_nerd_font_icons = true
show_preview_panel = false

[previewers.file]
# Default theme for bat.
theme = "Monokai Extended"

# Television already has some pretty Emacsy keybinds.
# This just makes them even more emacsier.
[keybindings.Channel]
scroll_preview_half_page_down = "alt-v"
scroll_preview_half_page_up = "ctrl-v"
toggle_remote_control = "alt-x"
toggle_help = "ctrl-h"

[keybindings.SendToChannel]
toggle_help = "ctrl-h"

[keybindings.RemoteControl]
toggle_remote_control = "alt-x"
toggle_help = "ctrl-h"

[shell_integration.channel_triggers]
"alias" = ["alias", "unalias"]
"env" = ["export", "unset"]
"dirs" = ["cd", "ls", "eza", "rmdir"]
"files" = [
  "cat",
  "less",
  "head",
  "tail",
  "vim",
  "nano",
  "bat",
  "cp",
  "mv",
  "rm",
  "touch",
  "chmod",
  "chown",
  "ln",
  "tar",
  "zip",
  "unzip",
  "gzip",
  "gunzip",
  "xz",
  "emacs",
  "$VISUAL",
  "$EDITOR",
]
"git-diff" = ["git add", "git restore"]
"git-branch" = [
  "git checkout",
  "git branch",
  "git merge",
  "git rebase",
  "git pull",
  "git push",
]
"podman-images" = ["podman run"]
"nixpkgs" = ["nix shell"]

[shell_integration.keybindings]
"smart_autocomplete" = "ctrl-t"
"command_history" = "ctrl-r"
