;;; Modus Themes Colors --- Generated with Matugen -*- lexical-binding: t; -*-

(use-package modus-themes
  :custom
  (modus-vivendi-palette-overrides
    `((bg-main "{{colors.surface.default.hex}}")
       (bg-dim "{{colors.surface_dim.default.hex}}")
       (fg-main "{{colors.on_surface.default.hex}}")
       (fg-dim fg-main)
       (fg-alt "{{colors.on_surface_variant.default.hex}}")
       (bg-active bg-main)
       (fg-active fg-main)
       (bg-inactive "{{colors.inverse_surface.default.hex}}")
       (fg-inactive "{{colors.on_surface_variant.default.hex}}")
       (border "{{colors.outline.default.hex}}")
       (bg-completion bg-main)
       (fg-completion "{{colors.shadow.default.hex}}")
       (bg-hover "{{colors.surface_container.default.hex}}")
       (fg-hover fg-main)
       (bg-region "{{colors.primary.default.hex}}")
       (fg-region "{{colors.on_primary.default.hex}}")
       (bg-mode-line-active bg-main)
       (fg-mode-line-active fg-main)
       (border-mode-line-active bg-main)
       (border-mode-line-inactive bg-main)
       (bg-mode-line-inactive bg-inactive)
       (fg-mode-line-inactive fg-inactive)
       (modeline-err red)
       (modeline-warning warning)
       (modeline-info info)
       (bg-tab-bar "{{colors.surface_container.default.hex}}")
       (bg-tab-bar-current "{{colors.surface_container_high.default.hex}}")
       (bg-tab-other "{{colors.surface_container_low.default.hex}}")
       (accent-0 "{{colors.primary.default.hex}}")
       (accent-1 "{{colors.secondary.default.hex}}")
       (accent-2 "{{colors.tertiary.default.hex}}")
       (accent-3 accent-2)
       ;; Catpuccin Mocha colors
       (rainbow-0 "#f38ba8")
       (rainbow-1 "#fab387")
       (rainbow-2 "#f9e2af")
       (rainbow-3 "#a6e3a1")
       (rianbow-4 "#94e2d5")
       (rainbow-5 "#74c7ec")
       (rainbow-6 "#89b4fa")
       (rainbow-7 "#cba6f7")
       (rainbow-8 "#b4befe"))))
