;;; Modus Themes Colors --- Generated with Matugen -*- lexical-binding: t; -*-

(use-package modus-themes
  :custom
  (modus-operandi-palette-overrides
   `((bg-main "{{colors.surface.light.hex}}")
     (bg-dim "{{colors.surface_dim.light.hex}}")
     (fg-main "{{colors.on_surface.light.hex}}")
     (fg-dim "{{colors.on_surface_variant.light.hex}}")
     (fg-alt "{{colors.outline.light.hex}}")
     (bg-active bg-main)
     (fg-active fg-main)
     (bg-inactive bg-main)
     (fg-inactive fg-main)
     (border "{{colors.outline.light.hex}}")
     (bg-completion bg-main)
     (fg-completion "{{colors.shadow.light.hex}}")
     (bg-hover "{{colors.surface_container.light.hex}}")
     (fg-hover fg-main)
     (bg-region "{{colors.primary.light.hex}}")
     (fg-region "{{colors.on_primary.light.hex}}")
     (bg-mode-line-active bg-main)
     (fg-mode-line-active fg-main)
     (border-mode-line-active bg-main)
     (border-mode-line-inactive bg-main)
     (bg-mode-line-inactive bg-inactive)
     (fg-mode-line-inactive fg-inactive)
     (modeline-err red)
     (modeline-warning warning)
     (modeline-info info)
     (bg-tab-bar "{{colors.surface_container.light.hex}}")
     (bg-tab-bar-current "{{colors.surface_container_high.light.hex}}")
     (bg-tab-other "{{colors.surface_container_low.light.hex}}")
     (accent-0 "{{colors.primary.light.hex}}")
     (accent-1 "{{colors.secondary.light.hex}}")
     (accent-2 "{{colors.tertiary.light.hex}}")
     (accent-3 "{{colors.tertiary.light.hex | set_lightness: -20.0}}")))
  (modus-vivendi-palette-overrides
   `((bg-main "{{colors.surface.dark.hex}}")
     (bg-dim "{{colors.surface_dim.dark.hex}}")
     (fg-main "{{colors.on_surface.dark.hex}}")
     (fg-dim "{{colors.on_surface_variant.dark.hex}}")
     (fg-alt "{{colors.outline.dark.hex}}")
     (bg-active bg-main)
     (fg-active fg-main)
     (bg-inactive bg-main)
     (fg-inactive fg-main)
     (border "{{colors.outline.dark.hex}}")
     (bg-completion bg-main)
     (fg-completion "{{colors.shadow.dark.hex}}")
     (bg-hover "{{colors.surface_container.dark.hex}}")
     (fg-hover fg-main)
     (bg-region "{{colors.primary.dark.hex}}")
     (fg-region "{{colors.on_primary.dark.hex}}")
     (bg-mode-line-active bg-main)
     (fg-mode-line-active fg-main)
     (border-mode-line-active bg-main)
     (border-mode-line-inactive bg-main)
     (bg-mode-line-inactive bg-inactive)
     (fg-mode-line-inactive fg-inactive)
     (modeline-err red)
     (modeline-warning warning)
     (modeline-info info)
     (bg-tab-bar "{{colors.surface_container.dark.hex}}")
     (bg-tab-bar-current "{{colors.surface_container_high.dark.hex}}")
     (bg-tab-other "{{colors.surface_container_low.dark.hex}}")
     (accent-0 "{{colors.primary.dark.hex}}")
     (accent-1 "{{colors.secondary.dark.hex}}")
     (accent-2 "{{colors.tertiary.dark.hex}}")
     (accent-3 "{{colors.tertiary.dark.hex | set_lightness: -20.0}}"))))
