#!/usr/bin/env -S guix shell coreutils -- sh

set -eu

# Variables.

lock_dir="${XDG_RUNTIME_DIR:-/tmp}"
waybar_indicator_file="$lock_dir/waybar-screen-record-indicator"

# Named pipe.

if [ ! -e "$waybar_indicator_file" ]; then
  mkfifo "$waybar_indicator_file"
fi

# Main script.

tail -f "$XDG_RUNTIME_DIR/waybar-screen-record-indicator"
